---
title: "Data acquisition for Project 2"
subtitle: "ME 597"
author: "Cheng Xu"
date:   "`r format(Sys.time(), '%Y--%m--%d')`"
output: github_document

---

```{r setup, include=FALSE}
library(knitr)
library(captioner)
library(plyr)
library(dplyr)
library(tidyverse)
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "../")
```


The original article is in the resource folder with the name "201_original_article.pdf"

##  2018-10-13 RAL

In discussing Figure 1, the authors state the data are from the "Flow of Funds Accounts maintained by the Federal Reserve." The note in the figure states "Source: Federal Reserve Flow of Funds Data; Bureau of Economic Analysis". I googled the latter and found a [data download program](https://www.federalreserve.gov/datadownload/Choose.aspx?rel=Z1). Using the Build Your Package feature I was able to find real estate assets owned by households with values similar to those in Table 1. 

For Table 2, I went to a [Robert Schiller website](http://www.econ.yale.edu/~shiller/data.htm) and clicked on the link for US home prices 1890-present which downloaded a spreadsheet that had data similar to that in Figure 2. This may not be exactly what you need, but it shows me that you could be more thorough in your search for the raw data than you have been so far. The spreadsheet also includes a column for the CPI. The CPI is a standard tool for adjusting dollar amounts for inflation. There will be numerous explanations online how to use it. 

I have two suggestions: 

- be more thorough in your own searches; and 
- ask our reference librarians for assistance. 

Obtaining the original data isn't easy but it is part of your responsibility for the project. As you obtain specific data sets, do the analysis, create the graph, and so forth. Work with what you have but continue to acquire any data you don't have. 



## 2018-10-10  Xu email

I found two issues with the data of project 2:

1.	I did find the data of S&P Case Shiller index used in the article. However, on the website, it only provides the 10-year long data for each month (2008 - 2018). However, in the article, it uses the data from 1975 - 2012. Also NO data on the website is similar to Table 2.
2.	For the data "FHFA index", author is not clear for which type he is using for "All Transactions". On the official website, it has many types.
3.	Author does not suggest where the Figure 1 from and NO such source printed in Table 1 from GOOGLE search. However, find similar data but not exact data for Table 1 and Figure 1 from google search.
4.	Author mentioned other data are from Investment Company Institute and "Moody’s Economy.com" and "Moodys .com". However, no such data on the website or getting them requires authorization or something else.






## Problem with the data acquisition part

1. The website https://fred.stlouisfed.org/series/CPGDPAI is a possible website for the data of the figure 1 in the original report. However, it is not quarterly and the earliest data is 2005 while in the original article, it uses the data from 1972 to 2012. 

1. For the Table 1, author says the source for this table is https://fred.stlouisfed.org/. However, I could not download the data of "Real Estate" on the website https://fred.stlouisfed.org/series/OEHRENWBSHNO. Also, author is not clear about how those numbers in the table come from.

2. For the figure 2 in the original report, I did find the data of S&P Case Shiller

3. For the figure 3 in the original report, I did find the data of FHFA Housing Price Index (All Transactions) on the website https://www.fhfa.gov/DataTools/Downloads/Pages/House-Price-Index-Datasets.aspx#qat. However there are many types of it on this website. Author does not mention which type he is using for "All Transactions".

4. For the figure 4,5,6,7 in the original report, author mentioned "the Fiserv Case Shiller Index". There is no such index on the website https://us.spindices.com/indices/real-estate/sp-corelogic-case-shiller-10-city-composite-home-price-nsa-index#global-login. Also there is no Case-Shiller index for Texas, California, Florida and Arizona. There is "Per Capita Personal Income" data on the website https://fred.stlouisfed.org/release?rid=151. However, the data is only available for 1998 to 2017 (Sep 25). But in the original report, he used the data 1975 - 2012.

5. For the figure 8,9,10, there are several sets of raw data: A) Housing Wealth. When I search for the data for "Current Population Survey and the 1990 and
2000 Census of Population and Housing", I got the website https://www.census.gov/prod/www/decennial.html. However, there is no useful data (or no data at all) in the "data section" of the website. B) Retail Sales. Author said the website Moody’s Economy.com. However, it seems to me that it requires authorization for the data. C) Financial Wealth. Author said they use two bodies of data, but he does not tell me what final dataset he used in the figure. Also, when I search on the website https://www.federalreserve.gov/default.htm. Either there is no data or the earliest data is 2005 for corporate equities, pension fund reserves, and mutual funds. D) Personal Income. Even I register an account on the website https://www.moodys.com/ I could not find any income data for the states (e.g. California) on this website. 

6. Finally, at the end of page 17, author mentioned "deflation using the CPI". I never see he used it or how this CPI related to the figures 8 through 10. 



